# Title of your blog; shows in the header
name:               "Gula Jawa"

# Description of your content (will only be used on Google Search)
description:        "where I blog about learning, coding, and ux"

# Your name. Will show in your footer + sidebar
author_name:        "Dr Kat Chuang"
author_email:       hello@katychuang.com
author_gravatar:    281f2d38dff2938dd450c08903b1e290 # Gravatar md5 hash
twitter_username:   norsasono
github_username:    norsasono 

url:                "http://macbookandheels.com"
baseurl:            ""
peramlink:          /:year/:month/:day/:title
timezone:           America/New_York 
#https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude these files from your production _site
exclude: [Gemfile, Gemfile.lock, CNAME, Readme.md]

author-bio: "floating adrift in a sea of zeroth world problems."

# Social Accounts
author:     katychuang
twitter:    katychuang
github:     katychuang
dribbble:   katychuang
instagram:  katychuang.nyc
facebook:   katychuang.nyc

# social feed settings
twitter_format: "@title: @url@tags"
twitter_url_length: 22
twitter_max_length: 140

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain:      katychuang.com/5min/
ga_tracking_id: 

# M&H domain
google_analytics:    # Put your Google Analytics code

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed
permalink: pretty
highlighter: rouge

paginate: 10
paginate_path: "/page/:num"

compress_html:
  clippings: all
  ignore:
    envs: ["test"]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
      share:        facebook # sharing on facebook by default

# SCSS

sass:
  sass_dir: _scss
  style: :compressed

gems: 
   - jekyll-paginate
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
